name: cffconvert

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  verify:
    name: "cffconvert"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out a copy of the repository

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
