name: markdown-link-check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.mlc-config.json'
