---
# profile selection
template_profile:
  type: str
  default: "recommended"
  help: Select a profile
  choices:
    Recommended (our defaults for research software): "recommended"
    Minimum (bare minimum, no extra features): "minimum"
    Let me choose (decide each feature yourself): "ask"
